# Generated by Django 5.1 on 2026-04-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='ephemeral',
            field=models.BooleanField(default=False),
        ),
    ]
