# Generated by Django 6.0.4 on 2026-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanresult_ephemeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
