# Generated by Django 6.0.4 on 2026-06-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_add_scan_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='deep_scan_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='deep_scan_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='deep_scan_findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='deep_scan_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='deep_scan_retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='deep_scan_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='deep_scan_status',
            field=models.CharField(choices=[('pending', 'Čeká'), ('running', 'Probíhá'), ('done', 'Dokončen'), ('failed', 'Selhal'), ('timeout', 'Vypršel'), ('skipped', 'Přeskočen')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='pre_deep_scan_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
