# Generated by Django 5.2.12 on 2026-06-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_deep_scan_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='accessibility_classification',
            field=models.CharField(choices=[('auto', 'Automaticky'), ('legal', 'Spadá pod zákon'), ('seo', 'Nespadá pod zákon')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='score_breakdown_computed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='score_legal',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='score_security',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='score_seo',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
